### PR TITLE
Bring back legacy Peatio benchmarks (closes #1189)

### LINKED ISSUE #1189: Bring back legacy Peatio benchmark
These benchmarks SHOULD NOT touch existing Peatio code. They must be isolated.

### PR DESCRIPTION
**Pull request by dinesh-skyach**
Bring back legacy Peatio benchmark

### CODE REVIEW

**Comment by yivo** [comment]
@dinesh-skyach 
It doesn't work for me after I have rebased the PR.

`LOG_LEVEL=warn be rake benchmark:execution`

```
>> Setup environment (executor=8 num=250 round=4)

>> Round 1
                           user     system      total        real
create members       rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Email has already been taken
/Users/yaroslav/Development/skyach-peatio/lib/benchmark/sweat_factory.rb:9:in `make_member'
/Users/yaroslav/Development/skyach-peatio/lib/benchmark/helpers.rb:8:in `block in create_members'
/Users/yaroslav/Development/skyach-peatio/lib/benchmark/helpers.rb:7:in `times'
/Users/yaroslav/Development/skyach-peatio/lib/benchmark/helpers.rb:7:in `create_members'
/Users/yaroslav/Development/skyach-peatio/lib/benchmark/matching.rb:25:in `block (3 levels) in run_prepare_orders'
/Users/yaroslav/Development/skyach-peatio/lib/benchmark/matching.rb:25:in `block (2 levels) in run_prepare_orders'
/Users/yaroslav/Development/skyach-peatio/lib/benchmark/matching.rb:24:in `block in run_prepare_orders'
/Users/yaroslav/Development/skyach-peatio/lib/benchmark/matching.rb:22:in `map'
/Users/yaroslav/Development/skyach-peatio/lib/benchmark/matching.rb:22:in `run_prepare_orders'
/Users/yaroslav/Development/skyach-peatio/lib/benchmark/matching.rb:15:in `run'
/Users/yaroslav/Development/skyach-peatio/lib/tasks/benchmark.rake:26:in `block (2 levels) in <top (required)>'
/Users/yaroslav/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
/Users/yaroslav/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
Tasks: TOP => benchmark:execution
(See full trace by running task with --trace)
```

**Comment by dinesh-skyach** [comment]
@yivo try running these tasks with fresh database.

**Comment by yivo** [comment]
@dinesh-skyach My DB is newly created. Can you clone this and try by yourself?

**Comment by dinesh-skyach** [comment]
@yivo, I did test this again and it worked for me with fresh database.

Please try these commands:- 
rake db:drop
rake db:create
rake db:migrate
rake currencies:seed
rake markets:seed
LOG_LEVEL=warn rake benchmark:execution

Please let me know if you still face this issue.

**Comment by yivo** [comment]
It fails randomly. Now I have the next problem:

See the gist with lgos: https://gist.github.com/yivo/ec5379ac458384d69b2961164d1b4ccb

**Comment by yivo** [comment]
@dinesh-skyach Can you try to use this for getting uniq values? https://github.com/stympy/faker#ensuring-unique-values

**Comment by dinesh-skyach** [comment]
@yivo I have added unique email for users.

And I have tested many times and did not get the "Mysql2::Error: Too many connections" Error

**Comment by yivo** [comment]
@dinesh-skyach Please, rebase the PR.

**Comment by dinesh-skyach** [comment]
@yivo I have rebased the PR.

**Comment by yivo** [comment]
@dinesh-skyach Can you please rebase again?

image

**Comment by dinesh-skyach** [comment]
@yivo done.

**Pull request merged**
