### PR TITLE
Remove lib/tasks/migration.rake

### PR DESCRIPTION
**Pull request by gfedorenko**

### CODE REVIEW

**Comment by mod** [comment]
seems like very valuable code
why removing ?

**Comment by yivo** [comment]
@mod 

`"set member activation from identity"` – no  more needed since we strip sign up via email
`"build auth to exist identites"` – the same
`"upgrade to new deposit-transaction schema"` – migration of existing trades
`"fix scopes of old api tokens"` – migration
`"fix order trades_count"` – migration
`"set history orders ord_type to limit"` – migration
`"update ask_member_id and bid_member_id of trades"` – migration (fixes missing member IDs) 
`"reset aasm_state of id_documents"` – the name tells about it does

**Comment by yivo** [comment]
So 7 of 8 are not needed, and the last one is one-line of code. So why keeping this file?

**Comment by mod** [comment]
@yivo I see, why thoses tasks aren't in migrations, are they connected somehow ?

**Comment by yivo** [comment]
@mod Peatio devs used these tasks to do some changes to their database when pushing new release. They were used to migrate to app newer features.

**Pull request merged**
