### PR TITLE
#206 and #207: Several Specs are failing due to MSSQL incompatibilities

### PR DESCRIPTION
**Pull request by dinesh-skyach**
[WIP] #206 and #207: Several Specs are failing due to MSSQL Incompatibilities

### CODE REVIEW

**Comment by yivo** [comment]
Hi. Is this PR still in progress?

**Comment by dinesh-skyach** [comment]
Hi @yivo, No It's completed.

**Comment by yivo** [comment]
@dinesh-skyach Have you checked that fiat & cryptocurrency deposit / trading / withdraws work as expected?

**Comment by dinesh-skyach** [comment]
Hi @yivo I have tested deposit/ trading /withdraw via adding the balance manually from backend and everything is working fine.

**Comment by yivo** [comment]
@dinesh-skyach Please update commit message to `Fix all MSSQL incompatibilities` and squash all commits into one.

**Pull request merged**
