### PR TITLE
Migrating to Bootstrap 4 + admin template

### PR DESCRIPTION
**Pull request by webmix**

### CODE REVIEW

**Comment by yivo** [comment]
@webmix bugs:

image

image

image

Ugly inputs
image

Blurry logo
image

Withdraw title is not clear
image

**Comment by yivo** [comment]
image

image

image

**Comment by webmix** [comment]
@yivo 
Update PR, though there are some elements I couldn't find.

Please let me know:
- Where is withdraw amount page? And what is the problem about the input ?
- I do not have SVG white logo. However, this PNG version looks blurry only if you zoom

all other stuff fixed (unless front, waiting for @mod recommendations), please let me know if everthing is ok

**Comment by yivo** [comment]
@webmix 
1. We don't have any withdraw amount page. You input withdraw info by clicking «Withdraw» at currency. If you found any zombie views – you can remove them. 
2. It looks blurry on screens with high PPI, like Macbook with retina. Maybe we can find any SVG?

**Comment by yivo** [comment]
@webmix 

image

**Comment by yivo** [comment]
image

**Comment by yivo** [comment]
@webmix two problems here: 1) email is not readable; 2) double «No», one should be «Yes»

image

image

**Comment by yivo** [comment]
Any margins? 

image

**Comment by yivo** [comment]
I think this is too white.

image

**Comment by yivo** [comment]
image

**Comment by yivo** [comment]
image

**Comment by yivo** [comment]
invalid hover color

image

**Comment by yivo** [comment]
too big and too white
image

**Comment by yivo** [comment]
@webmix Use SVG and CSS filter for logo in admin in case you don't have good SVG. Please, no PNG.

**Comment by yivo** [comment]
Something terrible with markets form (edit existing market):

image

**Comment by yivo** [comment]
button is very big, ever bigger than title lol

image
image

**Comment by yivo** [comment]
table is not readable

image

**Comment by yivo** [comment]
@webmix either do it responsive either disable responsive design and force scrollbars

image

image

**Comment by webmix** [comment]
New version pushed.
Let's maybe merge and fix small issues step by step to not block development

**Comment by yivo** [comment]
@webmix I have just rebased your PR.

**Pull request merged**
