### PR TITLE
[WIP] Markets page should update list of orders when order is created [devel branch]

### PR DESCRIPTION
**Pull request by amir-budaychiev**
[WIP] Markets page should update list of orders when order is created [devel branch]

### CODE REVIEW

**Comment by amir-budaychiev** [comment]
@yivo is it done? or changes needed?

**Comment by yivo** [comment]
Hello @amir-budaychiev 

No, it is not ready. You actually just removed useful code. You should implement feature which updates list of orders in realtime.

**Comment by amir-budaychiev** [comment]
Hello @yivo
I attached screencast which showing how works updating the orders in real time in the devel branch: https://drive.google.com/open?id=1Z7GXpZNyDtTR66WEZccUpb9RvI9moxfV. As you can see It works correct.
So, can you please explain me more about - why do you think that feature related with updates list of orders in realtime doesn't work correctly? If it possible, please, attach screenshot with comments. Thanks.

**Comment by yivo** [comment]
Hello @amir-budaychiev 

The story is: I open 2 windows with trading. In first create order, switch to second. I should see the order without page refresh. But it isn't rendered.

**Comment by amir-budaychiev** [comment]
@yivo understood, thanks. Let me check.

**Comment by amir-budaychiev** [comment]
@yivo I did it by your story. It still works fine for me. Let's check again via my screencast: https://drive.google.com/open?id=1Q_WICdDQ8Sk1NYtNLe5nm8jqxkB_7MA9

As you can see: I opened 2 windows and worked on devel branch, when I created order in the first window, it was added for both windows. I did it also for second window and it works fine too.

As you can see it works absolutely correct for me.

**Comment by amir-budaychiev** [comment]
Hello @yivo. 

Did you have a chance to check my previous comment?

**Comment by yivo** [comment]
Hello @amir-budaychiev 

Based on your screencast it seems like we had some issue with Pusher configuration. Thanks. We will ping you if new tasks will be available.

**Comment by ghost** [comment]
Is it finish?

**Comment by yivo** [comment]
@senisende It is closed, bug rejected.

**Comment by ghost** [comment]
@yivo Okey thanks.

**Pull request closed without merging**
