### PR TITLE
#395 Fixed few overlaps found

### PR DESCRIPTION
**Pull request by dinesh-skyach**
[WIP] #395 Fixed few overlaps found

### CODE REVIEW

**Comment by yivo** [comment]
Hi @dinesh-skyach 

PR does not fully fixes the issue:
screen shot 2018-02-24 at 8 36 35 pm

**Comment by dinesh-skyach** [comment]
Hi @yivo, I have made the changes and it is fixed now.

**Comment by yivo** [comment]
@dinesh-skyach Please squash all commits into one and put a name: `Fix few UI issues found at profile page & markets (issue #395).`.

**Comment by yivo** [comment]
@dinesh-skyach Still doesn't work: 
image

**Pull request merged**
