### PR TITLE
Dynamic fees concept

### PR DESCRIPTION
**Pull request by ysv**

### CODE REVIEW

**Comment by mod** [comment]
I don't understand why you would expose fees to the end-user trader

Also you need to explain which business case are you trying to solve.

take example of Rack middleware with method call()
I was thinking:
- customer create a gem MyDynamicFee
- gem holds a class call MyDynamicFee which implement method calculate() or call()
- in Initializer maybe we can dynamically register the peatio plugins
- In admin panel we specify the class to be called for fee calculation

if Customer want this fees lib can use external service like redis
Fee class is called in Trade executor, after trade you run
```
trade.fee = MyDynamicFee.call(trade_tuple)
```

**Comment by ysv** [comment]
@mod We will not expose fees to end user. This call will be removed from public API so we will create orders from Applogic via Management API
 https://github.com/rubykube/peatio/pull/1703/files#diff-143760e1eca712e2e4f00053aa493539R164

This call will be removed from public API so we will create orders from Applogic via Management API

Gem will not solve all business cases for example if we want to use referal program we need access to Applogic DB. 
What is more we will need to change Gemfile

**Comment by ysv** [comment]
What is more this model gives ability to track all fees of platform

**Comment by ysv** [comment]
Business cases solved

- [x] fixed fee for all customers, but we take XX% from fee and instead add it as bonus to parent user in referral program; e.g. as user I will be charged fixed fee, but percentage of that fee will go to user who invited me; 

- [x] user can pay fee in any cryptocurrency of their choice; when user choose to pay fee in CUSTOM token, he will get a fee discount configured by operator of platform; discount amount can be different depending on user's tier; check attachments for examples;

- [x] ability to pay fees with native exchange token (at a discount) and ability for user to select whether to pay fees with token or not

**Comment by ysv** [comment]
Closed we have another specs for this topic

**Pull request closed without merging**
