### PR TITLE
Make UI handle long deposit addresses

### PR DESCRIPTION
**Pull request by dinesh-skyach**
Fix Lil' problem for the key #453

### CODE REVIEW

**Comment by yivo** [comment]
@dinesh-skyach UI must handle long deposit addresses somehow. I think about truncation. Please, ensure it works like expected. Please, also update commit message to `Make UI handle long deposit addresses (issue #453).`.

**Comment by dinesh-skyach** [comment]
@yivo I have tested this for long deposit address and to handle long address I have used max-width and the content overflow is hidden. So the design is not spoiled.

In Addition you can copy the full address but will display limited address for long deposit address.

**Comment by yivo** [comment]
@dinesh-skyach Ok. I will clone and check it.

**Comment by ysv** [comment]
@dinesh-skyach @yivo I've tested
works fine for long addresses
deepinscreenshot_select-area_20180228160430

but doesn't for very long addresses
deepinscreenshot_select-area_20180228160450

but I'm not sure we need to handle such long addresses

**Comment by yivo** [comment]
@yssavchuk Could you please rebase it? We don't have New address btn anymore.

**Comment by yivo** [comment]
@dinesh-skyach ping

**Comment by ysv** [comment]
@yivo I can't rebase because I can't push to skyach:lil_problem_for_the_key

**Comment by yivo** [comment]
@yssavchuk OK. I have checked. It is up to date. Pls try cleaning your cache. We don't have «new address» button anymore.

**Comment by dinesh-skyach** [comment]
Hi @yivo, I have already rebased the PR and tested this for long addresses.

**Pull request merged**
