### PR TITLE
Remove trading UI leftovers in Peatio

### LINKED ISSUE #793: Remove trading UI leftovers in Peatio

### PR DESCRIPTION
**Pull request by k1T4eR**

### CODE REVIEW

**Review by yivo — CHANGES_REQUESTED** [review]
Please, rebase.

**Comment by yivo** [comment]
@k1T4eR 

image

**Comment by yivo** [comment]
@k1T4eR 

image

**Comment by yivo** [comment]
@k1T4eR I also see bootstrap-switch is only used in markets. In JS it is used in component_mixin directory. I think we can cleanup it well.

image

**Comment by k1T4eR** [comment]
@yivo 
1. market_light.scss was already removed before your comment!
2. custom/market.scss was already removed before your comment!!
3. features/_market.scss was already removed before your comment!!!
4. features/_market_chart.scss was already removed before your comment!!!!
5. ok, thanks. I'll check bootstrap-switch as well.

**Review by yivo — APPROVED** [review]

**Pull request merged**
