### PR TITLE
Add support for Litecoin

### PR DESCRIPTION
**Pull request by GildedHonour**

### CODE REVIEW

**Comment by yivo** [comment]
@GildedHonour Why have you picked these commits in your PR?

screen shot 2018-01-24 at 3 10 16 pm

Also fix PR's target branch according to specs.

**Comment by GildedHonour** [comment]
@yivo  Perhaps they were picked up automatically. I did this:

    git checkout -b issue_333 v2.0

which is creating  a branch 'issue_333' off the branch 'v2.0'

How should have I created it?

**Comment by GildedHonour** [comment]
Where do the figures from config/deposit_channels.yml and withdraw_channels.yml come from?

**Comment by GildedHonour** [comment]
A bit of a research shows that Litecoin has the plural form being litecoins.

**Comment by GildedHonour** [comment]
@yivo have you seen my questions?

**Comment by GildedHonour** [comment]
I'm almost finished with it. Should I squash my commits into a single one now or right before merging?

**Comment by yivo** [comment]
@GildedHonour Hello. If you want to ask something consider adding mentions for @yivo & @mkuvshynnikov. All configs are initially at lib/generators/configs.

I will check your code fast and then our QA will run the project and test new currency. As for now you can start next task – ETH support (also v2.0 branch).

**Comment by yivo** [comment]
@GildedHonour Please ping me when you are finished with LTC.

**Comment by GildedHonour** [comment]
@yivo 
Done. I haven't tested it because this time I have an exception when trying login via Auth0 -- "The url "http://fdsfdsfds/auth/auth0/callback" is not in the list of allowed callback URLs: http://localhost:3000/auth/auth0/callback, " -- perhaps someone has changed the domain name at the Auth0 dashboard for Peatio. 

Regarding JSON RPC -- if it's not compatible with BTC RPC I'll then need to implement it too.

**Comment by yivo** [comment]
@GildedHonour You will get login to work if you will open app via localhost. Do you know OAuth proto? Also you can set session manually.
I think LTC is compatible but I am not sure.

**Comment by GildedHonour** [comment]
@yivo I'm opening it locally: the app is running on my local machine. The thing is that it worked initially, I was able to register and login via Auth0, the next day -- not anymore.

**Comment by yivo** [comment]
@GildedHonour You can create session manually. What is the progress on this task? When you will finish. Ping @mkuvshynnikov please.

**Comment by GildedHonour** [comment]
@yivo I finished it 3 days ago and am working on #334. cc @mkuvshynnikov  
And I'll need to test it locally still, will do today.

**Comment by yivo** [comment]
@GildedHonour OK. Please, test it locally and ping me and @mkuvshynnikov. Thanks.

**Comment by GildedHonour** [comment]
@yivo  There's a bug in C++ boost lib and thus in litecon-qt too -- https://aur.archlinux.org/packages/litecoin-qt/ -- see the 2nd last comments. The patch didn't work for me. I'm looking for a workaround and then I'll be able to test it locally.

**Comment by yivo** [comment]
Continued in #402.

**Pull request closed without merging**
