### PR TITLE
Lock ruby version

### PR DESCRIPTION
**Pull request by yivo**

### CODE REVIEW

**Review by mod — CHANGES_REQUESTED** [review]
Hi @yivo I merged tests and they work with 2.2.2 now

**Comment by mod** [comment]
can you rebase and test the latest 2.2.X :-D @yivo

**Comment by yivo** [comment]
@mod 
```
Randomized with seed 48331
....................................................*...............................................Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4001,"message":"Did you forget to specify the cluster when creating the Pusher instance?  App key 50d404c35db92d736a57 does not exist in this cluster."}}}
..............*................*......***...........*............................................................***..........................................................................*.....................................................................................................................................................................................................................................................................................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Private::AssetsHelper add some examples to (or delete) /Users/yaroslav/Development/my-peatio/spec/helpers/private/assets_helper_spec.rb
     # Not yet implemented
     # ./spec/helpers/private/assets_helper_spec.rb:12

  2) PartialTree add some examples to (or delete) /Users/yaroslav/Development/my-peatio/spec/models/partial_tree_spec.rb
     # Not yet implemented
     # ./spec/models/partial_tree_spec.rb:2

  3) Sign in when a user has 2-step verification setup and after signing in with email, password if he tries to perform 2-step verification after session expires, should redirect user back to login step with error message
     # No reason given
     Failure/Error: fill_in 'two_factor_otp', with: two_factor.now

     Capybara::ElementNotFound:
       Unable to find visible field "two_factor_otp" that is not disabled
     # ./spec/features/sign_in_spec.rb:37:in `block (3 levels) in <top (required)>'

  4) withdraw admin approve withdraw
     # skip withdraw dashboard
     Failure/Error:
       within '.ops' do
         expect(page).to have_content(I18n.t('layouts.admin.menus.items.operating.withdraws'))
         click_on I18n.t('layouts.admin.menus.items.operating.withdraws')
       end

     Capybara::ElementNotFound:
       Unable to find visible css ".ops"
     # ./spec/features/admin/withdraw_spec.rb:21:in `visit_admin_withdraw_page'
     # ./spec/features/admin/withdraw_spec.rb:46:in `block (2 levels) in <top (required)>'

  5) withdraw admin view withdraws
     # skip withdraw dashboard
     Failure/Error:
       within '.ops' do
         expect(page).to have_content(I18n.t('layouts.admin.menus.items.operating.withdraws'))
         click_on I18n.t('layouts.admin.menus.items.operating.withdraws')
       end

     Capybara::ElementNotFound:
       Unable to find visible css ".ops"
     # ./spec/features/admin/withdraw_spec.rb:21:in `visit_admin_withdraw_page'
     # ./spec/features/admin/withdraw_spec.rb:30:in `block (2 levels) in <top (required)>'

  6) withdraw admin reject withdraw
     # skip withdraw dashboard
     Failure/Error:
       within '.ops' do
         expect(page).to have_content(I18n.t('layouts.admin.menus.items.operating.withdraws'))
         click_on I18n.t('layouts.admin.menus.items.operating.withdraws')
       end

     Capybara::ElementNotFound:
       Unable to find visible css ".ops"
     # ./spec/features/admin/withdraw_spec.rb:21:in `visit_admin_withdraw_page'
     # ./spec/features/admin/withdraw_spec.rb:65:in `block (2 levels) in <top (required)>'

  7) show account info user can cancel his own order
     # No reason given
     Got 0 failures and 2 other errors:

     7.1) Failure/Error: click_link page.all('#my_order_tabs_wrapper li').first.text

          NoMethodError:
            undefined method `text' for nil:NilClass
          # ./spec/features/market_trade_history_spec.rb:24:in `block (3 levels) in <top (required)>'
          # ./spec/features/market_trade_history_spec.rb:23:in `block (2 levels) in <top (required)>'

     7.2) Failure/Error: AMQPQueue.expects(:enqueue).with(:matching, action: 'cancel', order: ask_order.to_matching_attributes)

          MiniTest::Assertion:
            not all expectations were satisfied
            unsatisfied expectations:
            - expected exactly once, not yet invoked: AMQPQueue.enqueue(:matching, {:action => "cancel", :order => {:id => 483, :market => "btccny", :type => :ask, :ord_type => "limit", :volume => #<BigDecimal:0x7f8ffe741d10>, :price => #<BigDecimal:0x7f8ffe741e28>, :locked => #<BigDecimal:0x7f8ffcbd1c10>, :timestamp => 1511172380}})
            satisfied expectations:
            - allowed any number of times, invoked 6 times: AMQPQueue.publish(any_parameters)
            - allowed any number of times, not yet invoked: KlineDB.kline(any_parameters)
          # ./spec/features/market_trade_history_spec.rb:21:in `block (2 levels) in <top (required)>'

  8) 2-step verification allows user to set it up and disable it
     # No reason given
     Failure/Error:
       within '#two_factor_auth' do
         click_on I18n.t('private.settings.index.two_factor_auth.enable')
       end

     Capybara::ElementNotFound:
       Unable to find visible css "#two_factor_auth"
     # ./spec/features/two_factor_auth_spec.rb:12:in `block (2 levels) in <top (required)>'

  9) withdraw prevents withdraws that the account has no sufficient balance
     # No reason given
     Failure/Error: select 'Bank of China', from: 'withdraw_fund_extra'

     Capybara::ElementNotFound:
       Unable to find visible select box "withdraw_fund_extra" that is not disabled
     # ./spec/features/withdraw_spec.rb:65:in `submit_bank_withdraw_request'
     # ./spec/features/withdraw_spec.rb:57:in `block (2 levels) in <top (required)>'

  10) withdraw allows user to add a BTC withdraw address, withdraw BTC
      # No reason given
      Failure/Error: expect(page).to have_text('1000.0')
        expected #has_text?("1000.0") to return true, got false
      # ./spec/features/withdraw_spec.rb:32:in `block (2 levels) in <top (required)>'

  11) APIv2::Helpers#authentic? Authenticate using headers
     # Not yet implemented
     # ./spec/api/api_v2/helpers_spec.rb:20


Deprecation Warnings:

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /Users/yaroslav/Development/my-peatio/spec/models/worker/slave_book_spec.rb:46:in `block (3 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

1 deprecation warning total

Finished in 1 minute 41.89 seconds (files took 7.34 seconds to load)
648 examples, 0 failures, 11 pending

Randomized with seed 48331
```

**Comment by yivo** [comment]
```
Sending build context to Docker daemon  23.02MB
Step 1/18 : FROM ruby:2.2.8
2.2.8: Pulling from library/ruby
85b1f47fba49: Pull complete
ba6bd283713a: Pull complete
817c8cd48a09: Pull complete
47cc0ed96dc3: Pull complete
00233accc944: Pull complete
79aa3a7c3577: Pull complete
364bb4dbe137: Pull complete
Digest: sha256:bdcc3204ea706a1ec42f94226a1aad52b308dc2af6464487ccfb81f793597c82
Status: Downloaded newer image for ruby:2.2.8
 ---> 4ca3e7cd3103
Step 2/18 : MAINTAINER lbellet@heliostech.fr
 ---> Running in 37e2c555b845
 ---> 4a79844ff8c4
Removing intermediate container 37e2c555b845
Step 3/18 : ENV APP_HOME /home/app
 ---> Running in 1c2291daa12d
 ---> 78a063341cba
Removing intermediate container 1c2291daa12d
Step 4/18 : RUN groupadd -r app --gid=1000
 ---> Running in c6eeadbc5db0
 ---> 4d30ad1e6e6a
Removing intermediate container c6eeadbc5db0
Step 5/18 : RUN useradd -r -m -g app -d /home/app --uid=1000 app
 ---> Running in 9aaaa994096e
 ---> f7b68f542a08
Removing intermediate container 9aaaa994096e
Step 6/18 : RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
 ---> Running in b32f1cf8a4a4

## Installing the NodeSource Node.js v6.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [614 kB]
Ign http://deb.debian.org jessie InRelease
Get:3 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:4 http://deb.debian.org jessie Release.gpg [2373 B]
Get:5 http://deb.debian.org jessie Release [148 kB]
Get:6 http://deb.debian.org jessie-updates/main amd64 Packages [23.2 kB]
Get:7 http://deb.debian.org jessie/main amd64 Packages [9063 kB]
Fetched 10.1 MB in 6s (1557 kB/s)
Reading package lists...

## Installing packages required for setup: apt-transport-https lsb-release...

+ apt-get install -y apt-transport-https lsb-release > /dev/null 2>&1

## Confirming "jessie" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/jessie/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js v6.x repo...

+ echo 'deb https://deb.nodesource.com/node_6.x jessie main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_6.x jessie main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit http://security.debian.org jessie/updates InRelease
Get:1 https://deb.nodesource.com jessie InRelease [4631 B]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [614 kB]
Ign http://deb.debian.org jessie InRelease
Hit http://deb.debian.org jessie-updates InRelease
Hit http://deb.debian.org jessie Release.gpg
Hit http://deb.debian.org jessie Release
Get:3 https://deb.nodesource.com jessie/main Sources [20 B]
Get:4 https://deb.nodesource.com jessie/main amd64 Packages [1005 B]
Get:5 http://deb.debian.org jessie-updates/main amd64 Packages [23.2 kB]
Get:6 http://deb.debian.org jessie/main amd64 Packages [9063 kB]
Fetched 9706 kB in 6s (1505 kB/s)
Reading package lists...

## Run `apt-get install nodejs` (as root) to install Node.js v6.x and npm

 ---> 3b93c8207e22
Removing intermediate container b32f1cf8a4a4
Step 7/18 : RUN apt-get update && apt-get install -y   nodejs   libmysqlclient-dev   imagemagick   gsfonts
 ---> Running in f5ad56afc507
Hit http://security.debian.org jessie/updates InRelease
Hit https://deb.nodesource.com jessie InRelease
Get:1 http://security.debian.org jessie/updates/main amd64 Packages [614 kB]
Ign http://deb.debian.org jessie InRelease
Hit http://deb.debian.org jessie-updates InRelease
Hit http://deb.debian.org jessie Release.gpg
Get:2 https://deb.nodesource.com jessie/main Sources [20 B]
Get:3 https://deb.nodesource.com jessie/main amd64 Packages [1005 B]
Hit http://deb.debian.org jessie Release
Get:4 http://deb.debian.org jessie-updates/main amd64 Packages [23.2 kB]
Get:5 http://deb.debian.org jessie/main amd64 Packages [9063 kB]
Fetched 9701 kB in 6s (1428 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
libmysqlclient-dev is already the newest version.
Suggested packages:
  imagemagick-doc autotrace cups-bsd lpr lprng enscript ffmpeg gimp gnuplot
  grads graphviz groff-base hp2xx html2ps libwmf-bin mplayer povray radiance
  sane-utils texlive-base-bin transfig ufraw-batch xdg-utils
Recommended packages:
  ghostscript netpbm
The following NEW packages will be installed:
  gsfonts nodejs
The following packages will be upgraded:
  imagemagick imagemagick-6.q16
2 upgraded, 2 newly installed, 0 to remove and 14 not upgraded.
Need to get 14.0 MB of archives.
After this operation, 49.6 MB of additional disk space will be used.
Get:1 http://security.debian.org/ jessie/updates/main imagemagick amd64 8:6.8.9.9-5+deb8u11 [160 kB]
Get:2 https://deb.nodesource.com/node_6.x/ jessie/main nodejs amd64 6.12.0-1nodesource1 [9924 kB]
Get:3 http://security.debian.org/ jessie/updates/main imagemagick-6.q16 amd64 8:6.8.9.9-5+deb8u11 [513 kB]
Get:4 http://deb.debian.org/debian/ jessie/main gsfonts all 1:8.11+urwcyr1.0.7~pre44-4.2 [3364 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 14.0 MB in 4s (3178 kB/s)
Selecting previously unselected package gsfonts.
(Reading database ... 21223 files and directories currently installed.)
Preparing to unpack .../gsfonts_1%3a8.11+urwcyr1.0.7~pre44-4.2_all.deb ...
Unpacking gsfonts (1:8.11+urwcyr1.0.7~pre44-4.2) ...
Preparing to unpack .../imagemagick_8%3a6.8.9.9-5+deb8u11_amd64.deb ...
Unpacking imagemagick (8:6.8.9.9-5+deb8u11) over (8:6.8.9.9-5+deb8u10) ...
Preparing to unpack .../imagemagick-6.q16_8%3a6.8.9.9-5+deb8u11_amd64.deb ...
Unpacking imagemagick-6.q16 (8:6.8.9.9-5+deb8u11) over (8:6.8.9.9-5+deb8u10) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_6.12.0-1nodesource1_amd64.deb ...
Unpacking nodejs (6.12.0-1nodesource1) ...
Processing triggers for fontconfig (2.11.0-6.3+deb8u1) ...
Processing triggers for mime-support (3.58) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Setting up gsfonts (1:8.11+urwcyr1.0.7~pre44-4.2) ...
Setting up imagemagick-6.q16 (8:6.8.9.9-5+deb8u11) ...
Setting up imagemagick (8:6.8.9.9-5+deb8u11) ...
Setting up nodejs (6.12.0-1nodesource1) ...
 ---> ebfed12c638f
Removing intermediate container f5ad56afc507
Step 8/18 : WORKDIR $APP_HOME
 ---> 3783cec66f3f
Removing intermediate container b12f553723f9
Step 9/18 : COPY Gemfile Gemfile.lock $APP_HOME/
 ---> 1b3238377d25
Step 10/18 : RUN mkdir -p $APP_HOME/vendor/bundle
 ---> Running in cf0f1a78963f
 ---> b98cf494dfca
Removing intermediate container cf0f1a78963f
Step 11/18 : RUN bundle install --path vendor/bundle
 ---> Running in 728174566dd7
The git source `git://github.com/peatio/unread.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching gem metadata from https://rubygems.org/.........
Fetching git://github.com/peatio/unread.git
Fetching rake 12.3.0
Installing rake 12.3.0
Fetching aasm 3.4.0
Installing aasm 3.4.0
Fetching concurrent-ruby 1.0.5
Installing concurrent-ruby 1.0.5
Fetching i18n 0.9.1
Installing i18n 0.9.1
Fetching minitest 4.7.5
Installing minitest 4.7.5
Fetching multi_json 1.12.2
Installing multi_json 1.12.2
Fetching atomic 1.1.99
Installing atomic 1.1.99 with native extensions
Fetching thread_safe 0.1.3
Installing thread_safe 0.1.3
Fetching tzinfo 0.3.53
Installing tzinfo 0.3.53
Fetching activesupport 4.0.13
Installing activesupport 4.0.13
Fetching builder 3.1.4
Installing builder 3.1.4
Fetching erubis 2.7.0
Installing erubis 2.7.0
Fetching rack 1.5.5
Installing rack 1.5.5
Fetching rack-test 0.6.3
Installing rack-test 0.6.3
Fetching actionpack 4.0.13
Installing actionpack 4.0.13
Fetching mini_mime 1.0.0
Installing mini_mime 1.0.0
Fetching mail 2.7.0
Installing mail 2.7.0
Fetching actionmailer 4.0.13
Installing actionmailer 4.0.13
Fetching active_hash 1.5.2
Installing active_hash 1.5.2
Fetching activemodel 4.0.13
Installing activemodel 4.0.13
Fetching activerecord-deprecated_finders 1.0.4
Installing activerecord-deprecated_finders 1.0.4
Fetching arel 4.0.2
Installing arel 4.0.2
Fetching activerecord 4.0.13
Installing activerecord 4.0.13
Using bundler 1.16.0
Fetching thor 0.20.0
Installing thor 0.20.0
Fetching railties 4.0.13
Installing railties 4.0.13
Fetching hike 1.2.3
Installing hike 1.2.3
Fetching tilt 1.4.1
Installing tilt 1.4.1
Fetching sprockets 2.11.0
Installing sprockets 2.11.0
Fetching sprockets-rails 2.3.3
Installing sprockets-rails 2.3.3
Fetching rails 4.0.13
Installing rails 4.0.13
Fetching acts-as-taggable-on 3.0.1
Installing acts-as-taggable-on 3.0.1
Fetching public_suffix 3.0.1
Installing public_suffix 3.0.1
Fetching addressable 2.5.2
Installing addressable 2.5.2
Fetching amq-protocol 1.9.2
Installing amq-protocol 1.9.2
Fetching eventmachine 1.0.4
Installing eventmachine 1.0.4 with native extensions
Fetching amqp 1.3.0
Installing amqp 1.3.0
Fetching angularjs-rails 1.3.15
Installing angularjs-rails 1.3.15
Fetching awesome_print 1.2.0
Installing awesome_print 1.2.0
Fetching descendants_tracker 0.0.3
Installing descendants_tracker 0.0.3
Fetching ice_nine 0.11.0
Installing ice_nine 0.11.0
Fetching axiom-types 0.1.0
Installing axiom-types 0.1.0
Fetching bcrypt-ruby 3.1.2
Installing bcrypt-ruby 3.1.2 with native extensions
Fetching coderay 1.1.2
Installing coderay 1.1.2
Fetching erubi 1.7.0
Installing erubi 1.7.0
Fetching better_errors 2.4.0
Installing better_errors 2.4.0
Fetching debug_inspector 0.0.3
Installing debug_inspector 0.0.3 with native extensions
Fetching binding_of_caller 0.7.3
Installing binding_of_caller 0.7.3 with native extensions
Fetching sass 3.2.19
Installing sass 3.2.19
Fetching bootstrap-sass 3.2.0.2
Installing bootstrap-sass 3.2.0.2
Fetching bootstrap-wysihtml5-rails 0.3.1.23
Installing bootstrap-wysihtml5-rails 0.3.1.23
Fetching bourbon 3.2.4
Installing bourbon 3.2.4
Fetching browser 0.8.0
Installing browser 0.8.0
Fetching bunny 1.2.1
Installing bunny 1.2.1
Fetching byebug 9.1.0
Installing byebug 9.1.0 with native extensions
Fetching callsite 0.0.11
Installing callsite 0.0.11
Fetching cancancan 2.1.1
Installing cancancan 2.1.1
Fetching mini_portile2 2.3.0
Installing mini_portile2 2.3.0
Fetching nokogiri 1.8.1
Installing nokogiri 1.8.1 with native extensions
Fetching xpath 2.1.0
Installing xpath 2.1.0
Fetching capybara 2.15.4
Installing capybara 2.15.4
Fetching json 1.8.6
Installing json 1.8.6 with native extensions
Fetching mime-types 1.25.1
Installing mime-types 1.25.1
Fetching carrierwave 0.10.0
Installing carrierwave 0.10.0
Fetching ffi 1.9.18
Installing ffi 1.9.18 with native extensions
Fetching childprocess 0.8.0
Installing childprocess 0.8.0
Fetching chronic 0.10.2
Installing chronic 0.10.2
Fetching cliver 0.3.2
Installing cliver 0.3.2
Fetching coercible 1.0.0
Installing coercible 1.0.0
Fetching coffee-script-source 1.12.2
Installing coffee-script-source 1.12.2
Fetching execjs 2.7.0
Installing execjs 2.7.0
Fetching coffee-script 2.4.1
Installing coffee-script 2.4.1
Fetching coffee-rails 4.0.1
Installing coffee-rails 4.0.1
Fetching currencies 0.4.2
Installing currencies 0.4.2
Fetching countries 0.9.3
Installing countries 0.9.3
Fetching country_select 2.1.0
Installing country_select 2.1.0
Fetching daemons 1.1.9
Installing daemons 1.1.9
Fetching daemons-rails 1.2.1
Installing daemons-rails 1.2.1
Fetching database_cleaner 1.6.2
Installing database_cleaner 1.6.2
Fetching datagrid 1.5.7
Installing datagrid 1.5.7
Fetching diff-lcs 1.3
Installing diff-lcs 1.3
Fetching doorkeeper 1.4.1
Installing doorkeeper 1.4.1
Fetching dotenv 2.2.1
Installing dotenv 2.2.1
Fetching dotenv-rails 2.2.1
Installing dotenv-rails 2.2.1
Fetching structured_warnings 0.3.0
Installing structured_warnings 0.3.0
Fetching rubytree 0.8.3
Installing rubytree 0.8.3
Fetching easy_table 0.0.6
Installing easy_table 0.0.6
Fetching eco-source 1.1.0.rc.1
Installing eco-source 1.1.0.rc.1
Fetching eco 1.0.0
Installing eco 1.0.0
Fetching http_parser.rb 0.6.0
Installing http_parser.rb 0.6.0 with native extensions
Fetching em-websocket 0.5.1
Installing em-websocket 0.5.1
Fetching enumerize 0.8.0
Installing enumerize 0.8.0
Fetching equalizer 0.0.9
Installing equalizer 0.0.9
Fetching factory_bot 4.8.2
Installing factory_bot 4.8.2
Fetching factory_bot_rails 4.8.2
Installing factory_bot_rails 4.8.2
Fetching faker 1.4.3
Installing faker 1.4.3
Fetching figaro 0.7.0
Installing figaro 0.7.0
Fetching font-awesome-sass 4.7.0
Installing font-awesome-sass 4.7.0
Fetching globalize 4.0.0
Installing globalize 4.0.0
Fetching request_store 1.1.0
Installing request_store 1.1.0
Fetching gon 5.2.0
Installing gon 5.2.0
Fetching hashie 3.5.6
Installing hashie 3.5.6
Fetching multi_xml 0.5.5
Installing multi_xml 0.5.5
Fetching rack-accept 0.4.5
Installing rack-accept 0.4.5
Fetching rack-mount 0.8.3
Installing rack-mount 0.8.3
Fetching virtus 1.0.2
Installing virtus 1.0.2
Fetching grape 0.7.0
Installing grape 0.7.0
Fetching grape-entity 0.4.2
Installing grape-entity 0.4.2
Fetching kramdown 1.3.3
Installing kramdown 1.3.3
Fetching grape-swagger 0.7.2
Installing grape-swagger 0.7.2
Fetching http_accept_language 2.1.1
Installing http_accept_language 2.1.1
Fetching httpclient 2.8.3
Installing httpclient 2.8.3
Fetching jbuilder 2.6.4
Installing jbuilder 2.6.4
Fetching jquery-rails 3.1.4
Installing jquery-rails 3.1.4
Fetching sass-rails 4.0.3
Installing sass-rails 4.0.3
Fetching jquery-datatables-rails 3.4.0
Installing jquery-datatables-rails 3.4.0
Fetching jwt 1.2.0
Installing jwt 1.2.0
Fetching kaminari 0.17.0
Installing kaminari 0.17.0
Fetching launchy 2.4.3
Installing launchy 2.4.3
Fetching liability-proof 0.0.9
Installing liability-proof 0.0.9
Fetching mails_viewer 0.1.2
Installing mails_viewer 0.1.2
Fetching rack-contrib 1.8.0
Installing rack-contrib 1.8.0
Fetching meta_request 0.4.3
Installing meta_request 0.4.3
Fetching metaclass 0.0.4
Installing metaclass 0.0.4
Fetching method_source 0.9.0
Installing method_source 0.9.0
Fetching mocha 1.3.0
Installing mocha 1.3.0
Fetching momentjs-rails 2.5.1
Installing momentjs-rails 2.5.1
Fetching mysql2 0.3.21
Installing mysql2 0.3.21 with native extensions
Fetching omniauth 1.2.2
Installing omniauth 1.2.2
Fetching omniauth-identity 1.1.1
Installing omniauth-identity 1.1.1
Fetching paper_trail 3.0.1
Installing paper_trail 3.0.1
Fetching paranoid2 1.1.3
Installing paranoid2 1.1.3
Fetching phonelib 0.3.5
Installing phonelib 0.3.5
Fetching websocket-extensions 0.1.3
Installing websocket-extensions 0.1.3
Fetching websocket-driver 0.7.0
Installing websocket-driver 0.7.0 with native extensions
Fetching poltergeist 1.16.0
Installing poltergeist 1.16.0
Fetching power_assert 1.1.1
Installing power_assert 1.1.1
Fetching pry 0.11.2
Installing pry 0.11.2
Fetching pry-rails 0.3.6
Installing pry-rails 0.3.6
Fetching pusher-signature 0.1.8
Installing pusher-signature 0.1.8
Fetching pusher 1.3.1
Installing pusher 1.3.1
Fetching quiet_assets 1.1.0
Installing quiet_assets 1.1.0
Fetching rack-attack 3.0.0
Installing rack-attack 3.0.0
Fetching rails-i18n 4.0.1
Installing rails-i18n 4.0.1
Fetching rails-observers 0.1.2
Installing rails-observers 0.1.2
Fetching rbtree 0.4.2
Installing rbtree 0.4.2 with native extensions
Fetching rdoc 4.1.1
Installing rdoc 4.1.1
Fetching redis 4.0.1
Installing redis 4.0.1
Fetching redis-store 1.4.1
Installing redis-store 1.4.1
Fetching redis-rack 2.0.3
Installing redis-rack 2.0.3
Fetching redis-actionpack 5.0.2
Installing redis-actionpack 5.0.2
Fetching redis-activesupport 5.0.4
Installing redis-activesupport 5.0.4
Fetching redis-rails 5.0.2
Installing redis-rails 5.0.2
Fetching rest-client 1.6.8
Installing rest-client 1.6.8
Fetching rotp 3.3.0
Installing rotp 3.3.0
Fetching rspec-support 3.7.0
Installing rspec-support 3.7.0
Fetching rspec-core 3.7.0
Installing rspec-core 3.7.0
Fetching rspec-expectations 3.7.0
Installing rspec-expectations 3.7.0
Fetching rspec-mocks 3.7.0
Installing rspec-mocks 3.7.0
Fetching rspec-rails 3.7.1
Installing rspec-rails 3.7.1
Fetching rubyzip 1.2.1
Installing rubyzip 1.2.1
Fetching selenium-webdriver 3.7.0
Installing selenium-webdriver 3.7.0
Fetching shoulda-matchers 3.1.2
Installing shoulda-matchers 3.1.2
Fetching simple_captcha2 0.2.2
Installing simple_captcha2 0.2.2
Fetching simple_form 3.1.0
Installing simple_form 3.1.0
Fetching temple 0.6.7
Installing temple 0.6.7
Fetching slim 2.0.2
Installing slim 2.0.2
Fetching slim-rails 2.1.0
Installing slim-rails 2.1.0
Fetching test-unit 3.2.6
Installing test-unit 3.2.6
Fetching timecop 0.9.1
Installing timecop 0.9.1
Fetching twilio-ruby 3.11.5
Installing twilio-ruby 3.11.5
Fetching uglifier 3.2.0
Installing uglifier 3.2.0
Using unread 0.4.0 from git://github.com/peatio/unread.git (at master@b8fa050)
Fetching whenever 0.9.2
Installing whenever 0.9.2
Bundle complete! 81 Gemfile dependencies, 174 gems now installed.
Bundled gems are installed into `./vendor/bundle`
Post-install message from atomic:
This gem has been deprecated and merged into Concurrent Ruby (http://concurrent-ruby.com).
Post-install message from acts-as-taggable-on:
When upgrading

Re-run the migrations generator

    rake acts_as_taggable_on_engine:install:migrations

It will create any new migrations and skip existing ones
Post-install message from rubytree:
    ========================================================================
                    Thank you for installing rubytree.

    Note that the TreeNode#siblings method has changed in 0.8.3.
    It now returns an empty array for the root node.

                 WARNING: SIGNIFICANT API CHANGE in 0.8.0 !
                 ------------------------------------------

    Please note that as of 0.8.0 the CamelCase method names are DEPRECATED.
    The new method names follow the ruby_convention (separated by '_').

    The old CamelCase methods still work (a warning will be displayed),
    but may go away in the future.

    Details of the API changes are documented in the API-CHANGES file.
    ========================================================================
Post-install message from globalize:

Globalize has extracted versioning support to a separate gem named
globalize-versioning. If you are using versioning (with paper_trail
or any other versioning gem), please add the line
"gem 'globalize-versioning'" to your Gemfile and go to the github
page at globalize/globalize-versioning if you encounter any problems.

Note that the globalize-versioning gem does not delegate versions to
the translation table, so you will have to update your syntax to
the form: `post.translation.versions`. See the globalize-versioning
readme for details.

Post-install message from phonelib:
    IMPORTANT NOTICE!
    Phone types were changed from camel case to snake case!
    Example: ":tollFree" changed to ":toll_free".
    Please update your app in case you are checking types!
Post-install message from rdoc:
Depending on your version of ruby, you may need to install ruby rdoc/ri data:

<= 1.8.6 : unsupported
 = 1.8.7 : gem install rdoc-data; rdoc-data --install
 = 1.9.1 : gem install rdoc-data; rdoc-data --install
>= 1.9.2 : nothing to do! Yay!
 ---> 61f60ad7be75
Removing intermediate container 728174566dd7
Step 12/18 : COPY . $APP_HOME
 ---> 39802b57321b
Step 13/18 : RUN chown -R app:app /home/app
 ---> Running in 02b76d320362
 ---> 60e4cff2271e
Removing intermediate container 02b76d320362
Step 14/18 : USER app
 ---> Running in 287b97c253e7
 ---> f8f6c801d196
Removing intermediate container 287b97c253e7
Step 15/18 : RUN ./bin/init_config
 ---> Running in 24a1956ea43e
[INFO] config/banks.yml exist. Replacing...
> cp config/banks.yml.example config/banks.yml
[INFO] config/currencies.yml exist. Replacing...
> cp config/currencies.yml.example config/currencies.yml
[INFO] config/amqp.yml exist. Replacing...
> cp config/amqp.yml.example config/amqp.yml
[INFO] config/markets.yml exist. Replacing...
> cp config/markets.yml.example config/markets.yml
[INFO] config/application.yml exist. Replacing...
> cp config/application.yml.example config/application.yml
 ---> e57775d795c1
Removing intermediate container 24a1956ea43e
Step 16/18 : EXPOSE 8080
 ---> Running in 28f513b039e2
 ---> 624ebb46ffdf
Removing intermediate container 28f513b039e2
Step 17/18 : ENTRYPOINT bundle exec
 ---> Running in 7f5893279701
 ---> caa2954b3120
Removing intermediate container 7f5893279701
Step 18/18 : CMD rails s -p 8080 -b 0.0.0.0
 ---> Running in 96937a827f54
 ---> 6c99faec268d
Removing intermediate container 96937a827f54
Successfully built 6c99faec268d
Successfully tagged peatio:latest
```

**Pull request merged**
