### PR TITLE
[WIP] Removed eco gem and installed ejs gem

### PR DESCRIPTION
**Pull request by rklymenko**

### CODE REVIEW

**Comment by rklymenko** [comment]
Hi @yivo I created new fork from project. And did same changes as in previous fork. And after finish rspecs - I see next result 
```
Finished in 1 minute 21.25 seconds (files took 4.88 seconds to load)
532 examples, 0 failures, 8 pending
```
but travis-ci said that "All checks have failed". What happens?

**Comment by rklymenko** [comment]
@yivo same result of rspec I have in the master branch

**Comment by yivo** [comment]
Linked PR #358.

**Comment by yivo** [comment]
@rklymenko I see another results: `532 examples, 5 failures, 8 pending`.
Could you please check the task once again?

**Comment by rklymenko** [comment]
@yivo Did you clone project from my branch? because I checked several times and I have same result

**Comment by yivo** [comment]
@rklymenko The reason your specs are failing is your changes to files. You should check task requirements again.

**Comment by rklymenko** [comment]
@yivo did you clone my branch? and run rspec for it?

**Pull request closed without merging**
