### PR TITLE
Parity Support instead of Geth

### PR DESCRIPTION
**Pull request by adarshdubeytech**
You can use Parity with this branch
Parity is a best alternative of geth.
Parity takes less than 1 hour to sync from 0 to current block.
A request to rubykube team by me :
Start using parity instead of geth in future releases!

### CODE REVIEW

**Comment by ysv** [comment]
@adarshdubeytech Thanks for your contribution 
Does it works with geth too ?

**Comment by adarshdubeytech** [comment]
> @adarshdubeytech Thanks for your contribution
> Does it works with geth too ?

For Geth we have to make it back to integer 5 instead of hex '0x5'
I think you guys can create a new client as parity and there will be 2 options in peatio for eth (parity and geth) the user will chose which they want to use.

Geth uses 5, and parity uses 0x5(hex only)

**Comment by mod** [comment]
We will work on that, thanks for the hint

**Comment by ysv** [comment]
@adarshdubeytech we can't drop geth support but in our plans is to add parity as separate WalletClient & BlockchainClient

**Comment by ysv** [comment]
progress in #1886

**Comment by adarshdubeytech** [comment]
> progress in #1886

Nice

**Pull request closed without merging**
