### PR TITLE
Added new scrypt-based BON coin

### PR DESCRIPTION
**Pull request by mseroka**

### CODE REVIEW

**Comment by mod** [comment]
@ysv shouldn't we advice a plugeable approach using a gem for adding those type of coin
also I think this coin works with bitcoin controller no need to change code here

**Comment by mseroka** [comment]
> @ysv shouldn't we advice a plugeable approach using a gem for adding those type of coin
> also I think this coin works with bitcoin controller no need to change code here
@mod: no, unfortunately it didn't work with bitcoin controller. all these changes is the minimum required for bon to work with peatio.

**Comment by ysv** [comment]
@mseroka Hello we want peatio to support only base currencies and give an ability to extend this by plugins
We are working on improving plugin system once it ready we will try to provide some custom coin support with peatio plugin

This may require some changes in peatio

**Comment by ysv** [comment]
@mseroka Can you close this pr ?
We are not going to have this coin in Peatio master but you are welcome to implement in as a plugin once we make Peatio ready for this

**Pull request closed without merging**
