### PR TITLE
bitcoin json client: pass endpoint path if provided

### LINKED ISSUE #2511: Bitcoin & ethereum JSON RPC client should pass endpoint path if provided
Bitcoin versions since v0.15 support multiple wallets over the RPC by using ./wallet/$WALLETNAME as the url path. Currently it's not possible to use these URL's with peatio because the client passes the hard coded path '/' in the request. 
https://github.com/openware/peatio/blob/e811e643349f330f8ba42a21040ad9b1edffa783/lib/peatio/bitcoin/client.rb#L22

I've made a PR for this https://github.com/openware/peatio/pull/2512

Per comments from @mikoim (and @martianatwork I think), I've done the same for the ethereum client.

### PR DESCRIPTION
**Pull request by afk11**
Fixes #2511

First contribution here, let me know if I should follow up with tests

### CODE REVIEW

**Comment by mikoim** [comment]
@afk11 Ethereum client has same issue. Could you add patch for this?
https://github.com/openware/peatio/blob/master/lib/peatio/ethereum/client.rb#L23

**Comment by afk11** [comment]
Hey @mikoim - thanks for the tip. I hadn't run into it in geth as it has the keystore.. Is there a doc I can check to make sure it's the case? something like this https://github.com/bitcoin/bitcoin/blob/97aadf98d0b890e09eff45535fa13a663f27334d/src/bitcoin-cli.cpp#L59

**Comment by mikoim** [comment]
@afk11 At least Geth does not have a similar option. I've run multiple Ethereum nodes behind a  proxy and determine them by the path, as shown below.

```
http://proxy/mainnet/node-a
http://proxy/ropsten/node-b
...
```

**Comment by afk11** [comment]
Ah, I guess that makes sense :) I'll add it too so

**Comment by afk11** [comment]
Hmm, I guess I opened the PR against master, but I can rebase over other branches still in maintenance mode + submit PR's for those too.

**Comment by mnaichuk** [comment]
@afk11 can you prepare PR on 2-4-stable too?
we will merge it too

**Comment by afk11** [comment]
> @afk11 can you prepare PR on 2-4-stable too?
> we will merge it too

thanks, I have done this now

**Pull request closed without merging**
