### PR TITLE
add futures market support

### PR DESCRIPTION
**Pull request by hardywu**
works still needed to rebase to the latest 2.0 version. Throw any ideas if you have.

- [x]  rebase to v2.0 for merging
- [x]  positions api
- [x]  test scripts

### CODE REVIEW

**Comment by mod** [comment]
Hello,
That's interesting, can we define specs in markdown, or in the wiki ?

**Comment by hardywu** [comment]
@mod  wiki at https://github.com/rubykube/peatio/wiki/Proposal-for-Futures-Marktet-Specs

**Comment by mod** [comment]
I will study the topic, we can jump on a call together.
I need to see the interest of our community and customers in this feature as well.
Ideally this feature could be pluggable or have the ability to disable

Do you think it's achievable to make a table of "Futures" orders that will be specifically Futures ?
I am assuming it can use the trades.

**Comment by ysv** [comment]
@hardywu Could you open the issue where we can discuss this feature ?

**Comment by ysv** [comment]
@hardywu Could you updates us about your progress ?

**Comment by hardywu** [comment]
@ysv It is basically done.

**Comment by ianeinser** [comment]
> @ysv It is basically done.

Bring it on Dudes.. please for both v1.9 and v2.0

**Comment by hardywu** [comment]
@ysv any comments

**Comment by ysv** [comment]
@hardywu I will review thanks !

**Comment by ianeinser** [comment]
@hardywu Bro, there are conflicting files, would you mind checking. I would love to seeing this feature coming in rubykube

**Comment by nikharR** [comment]
> > @ysv It is basically done.
> 
> Bring it on Dudes.. please for both v1.9 and v2.0

+1 Here. Would be awesome to have 1.9 compatibility!

**Pull request closed without merging**
