### PR TITLE
Event API serializers imporvements (closes #1376, #1396)

### LINKED ISSUE #1376: Adding to event api new message when account changes
Can add to event_api message which publish when account changes (balance/locked)?

### PR DESCRIPTION
**Pull request by tamadamas**
Implemented #1376 and #1396 issues

### CODE REVIEW

**Comment by mod** [comment]
this is looking good, but is it necessary in v1.8 ? @rxx

**Comment by tamadamas** [comment]
I'm not sure. @ElviraMiro probably knows.

**Comment by tamadamas** [comment]
@mod It should be merged ASAP. I remember she said they need it for react things

**Comment by ysv** [comment]
@rxx We need the same PR for master branch

**Comment by mod** [comment]
@rxx can you make the PR on master?

**Pull request merged**
