### PR TITLE
Plugable NXT/WCG coins

### PR DESCRIPTION
**Pull request by dinesh-skyach**
Plugable NXT/WCG coins

### CODE REVIEW

**Comment by huuhait** [comment]
can u add support USDT (Tether)?

**Comment by pkucherenk0** [comment]
The NXT/WCG have the feature to, from what I understand, emulate the multi-sign wallet.
The main idea is that to perform withdraw successfully you will require approval from one or more other accounts under different conditions. 

What is crucial for us is that this feature actually sends the transaction in the blockchain before it receives the required amount of approvals and will wait a certain amount of blocks to receive them before been failed. This amount of blocks "Minimum and maximum phasing durations" can be set up manually and with the bigger amount of blocks then Peatio require to consider deposit successful. 

Expected result when receiving such transaction : 
Before considering this a successful transaction check for approval requirements and if they where met after what count the minimum blocks required.

Actual result:
Peatio will count minimum blocks required to consider deposit successful and ignore the approval requirements which can lead to a failed transaction in the blockchain afterwords.
The amount of deposit will be saved in DB and user will be able to withdraw this amount from the Hot wallet.

[Video about how to set multi-sign wallet in NXT.](https://www.youtube.com/watch?v=z0J1uuJL_5I)

**Comment by ysv** [comment]
closed ability to add custom coins will be implemented via coin plugins

**Comment by ysv** [comment]
closed in #2168

**Pull request closed without merging**
