### PR TITLE
Remove lib/tasks/emu.rake

### PR DESCRIPTION
**Pull request by spavlishak**

### CODE REVIEW

**Comment by yivo** [comment]
@spavlishak Please update commit to `Remove lib/tasks/emu.rake (fixes #232)`.

**Comment by mod** [comment]
Looks useful

**Comment by yivo** [comment]
@mod It is very old file, ever compared to peatio/peatio master.

**Comment by mod** [comment]
but I think we should have a similar functionality, maybe through feeders.

**Comment by yivo** [comment]
Closing the PR as it haven't received feedback more than a week.

**Pull request closed without merging**
