### PR TITLE
Remove Peatio.tech brand from admin panel

### PR DESCRIPTION
**Pull request by shal**

### CODE REVIEW

**Review by ysv — APPROVED** [review]

**Review by mod — COMMENTED** [review]
I would like to avoid logo

**Comment by ysv** [comment]
@mod does it make sense to customize text but not icon ?
screen shot 2019-02-19 at 4 39 57 pm

**Comment by mod** [comment]
Maybe we just write Admin and that's all ?

**Comment by ysv** [comment]
@shal how does it look now ?

**Comment by shal** [comment]
@ysv Just "**Admin**" instead of "**Peatio.tech**" and no more icons/logos.
We can push `micro-1` and take a look if needed

**Review by ysv — APPROVED** [review]

**Review by mod — APPROVED** [review]

**Pull request merged**
