### PR TITLE
Update aasm to 4.x

### PR DESCRIPTION
**Pull request by ysv**

### CODE REVIEW

**Comment by yivo** [comment]
@yssavchuk Pls change the branch to devel.

**Comment by yivo** [comment]
@mkuvshynnikov We need hard testing for this since it is major change.

**Comment by yivo** [comment]
@yssavchuk Please rebase to the latest devel.

**Comment by yivo** [comment]
@yssavchuk Have you rebased? Ping me pls.

**Comment by yivo** [comment]
@mkuvshynnikov @yssavchuk ping

**Comment by ysv** [comment]
@yivo rebased

**Comment by yivo** [comment]
Tested manually by myself. Works well.

**Pull request merged**
