### PR TITLE
[WIP] hot_wallets daemon doesn't work because exception is raised when using Ripple JSON RPC

### PR DESCRIPTION
**Pull request by vpetrusenko**

### CODE REVIEW

**Comment by yivo** [comment]
@vpetrusenko why there are some commits related to 2fa in your PR?

**Comment by vpetrusenko** [comment]
@yivo sorry have some troubles with my fork, should i squash it?

**Comment by yivo** [comment]
@vpetrusenko Could you please remove these commit from PR entirely?

**Comment by vpetrusenko** [comment]
@yivo Hello, i think the problem is that account is not activated yet, but activation service temporarily unavailable (https://bithomp.com/activation/)

**Comment by yivo** [comment]
@vpetrusenko Thanks.

@dkkoval Could you please check this?

**Comment by yivo** [comment]
Fixed by PR #141 which ships updated URLs for Ripple APIs.

**Pull request closed without merging**
