### PR TITLE
Currencies dead code clean up

### PR DESCRIPTION
**Pull request by dinesh-skyach**
Clean up dead code

### CODE REVIEW

**Comment by pkucherenk0** [comment]
Everything looks good.
I assume we should unblock fields in "Currencies":
selection_586
Since simple mistake will make as to Disable the currencies and make it dead wait but to update it and make it work. Also you will not be able to add "Wallet" if the "Currency id" is to long.

**Comment by dinesh-skyach** [comment]
@pkucherenk0 you mean to disable these fields? @ysv what are your thought on this?
 Also for long curreny_id issue, it's related to this https://github.com/rubykube/peatio/issues/1499

**Comment by pkucherenk0** [comment]
I want to be able to change the values in this fields. 
The withdraw is in the forever conformation. I have reached block difference in 240+ block and my withdraw are not confirmed, required only 6 blocks.

**Comment by ysv** [comment]
@dinesh-skyach @pkucherenk0 No we can't unblock this fields

**Comment by NQA1** [comment]
Here is the screenshot when we submit Wallet with lengthy currency Name: 
screen shot 2018-08-13 at 5 13 26 pm

**Comment by dinesh-skyach** [comment]
@NQA1 This issue relates to https://github.com/rubykube/peatio/issues/1499

**Pull request merged**
