### PR TITLE
Fix: #2851 Migrate all decimal(32,16) fields in Peatio to decimal(32,…

### LINKED ISSUE #2851: Peatio rounds ETH amounts to 16 decimal points
The bug was found using the opendax 2-4-stable branch with eth mainnet.

We've sent deposit to the User's deposit address, the amount received is 20447946344588791 Wei. According to etherscan.

This is 0,020447946344588791 Ether (18 decimal places)

Collection fee daemon logs:
{"level":"WARN","time":"2021-03-05 09:53:03","message":"The deposit was spreaded in the next way: [{:to_address=>\"0xb1bf8eaab5d4c7d8608df400938bcba30c91ea0e\", :amount=>\"0.0204479463445888\", :currency_id=>\"eth\", :status=>\"pending\"}]"}

Collection daemon logs:
#<Peatio::Wallet::ClientError: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 20447946344588800 and got: 20447946344588791. (-32010)>"}

As you can see the Deposit amount has been rounded from 18 decimal places (0,020447946344588791) to 16 decimal places (0.0204479463445888) which is incorrect as in ethereum network the decimal limits is 18 NOT 16.

This problem has been caused by the MySQL Database fields configuration which is decimal(32,16) e.g. 16 decimal places.

So in case the number is more than 16 decimal places and it gets round UP, then deposit is uncollectable

The issue should be fixed for both deposits and withdraws

My view of a fix is to bump up all fields with decimal(32,16) to decimal(32,18), and add tests which check that numbers with 18 decimal places in ETH get parsed correctly by the system.

### PR DESCRIPTION
**Pull request by antonDigitalMagic**
…18) to support ETH 18 decimal points precision
Fixes #2851

### CODE REVIEW

**Comment by mnaichuk** [comment]
Hello @antonDigitalMagic, we would change only deposits amount decimal scale because other changes will require to change in other repos.

**Comment by antonDigitalMagic** [comment]
> Hello @antonDigitalMagic, we would change only deposits amount decimal scale because other changes will require to change in other repos.

Could you please describe this in more details?

**Comment by mnaichuk** [comment]
> > Hello @antonDigitalMagic, we would change only deposits amount decimal scale because other changes will require to change in other repos.
> 
> Could you please describe this in more details?

I think for now would be enough to change only the deposit amount column and we don't need to change all decimal columns in peatio.

**Comment by antonDigitalMagic** [comment]
> > > Hello @antonDigitalMagic, we would change only deposits amount decimal scale because other changes will require to change in other repos.
> > 
> > 
> > Could you please describe this in more details?
> 
> I think for now would be enough to change only the deposit amount column and we don't need to change all decimal columns in peatio.

If we will change only amount, then the number will get rounded somewhere else, which will introduce inconsistencies in the amounts processed through the platform.

We need to either adjust the logic working with ETH deposits or change the column types in the DB. MySQL does not allow to change rounding type, therefore we either increase the amount of decimals, or parse the number prior saving to DB.

Any partial fix could introduce new issues.

**Comment by antonDigitalMagic** [comment]
@mnaichuk We can also fix this, as I've mentioned earlier without changing the DB schema, by using the same method for rounding as in trade engine.

trading/matching/engine.rb

```ruby
def round(d) 
        d.round(Market::DB_DECIMAL_PRECISION, BigDecimal::ROUND_DOWN) 
end
```

We can introduce the same functionality when taking the amount of ETH from blockchain. This is done in lib/peatio/ethereum/blockchain.rb

```ruby
def convert_from_base_unit(value, currency)
      value.to_d / currency.fetch(:base_factor).to_d
end
```

So currently it just converts wei to ethereum using base factor, but we can add rounding rules here, to always be sure, that when we read amount from blockchain it is rounded correctly.

```ruby
DB_DECIMAL_PRECISION = 16

def convert_from_base_unit(value, currency)
      (value.to_d / currency.fetch(:base_factor).to_d)
          .round(DB_DECIMAL_PRECISION, BigDecimal::ROUND_DOWN)
end
```
What do you think about such fix?

**Comment by mnaichuk** [comment]
@antonDigitalMagic thank you for the suggestions. We will discuss this with the team and will make a decision.

**Comment by calj** [comment]
Thanks for moving this topic forward.
I think we only need to increase the precision on deposits, the only known problem with precision was on very low precision deposits on ETH and ERC20.
Then the platform can work fine with 16 digits decimals for trading, accounts and withdrawals.
Migrating orders and trades tables can be pretty heavy on platforms with lot of data, we prefer to avoid changes to those tables if possible.

**Pull request closed without merging**
