### PR TITLE
Update setup-ubuntu.md

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/bundler/bundler/issues/4462

### CODE REVIEW

**Comment by shal** [comment]
@Fair-Exchange Well, thanks for contribution! Could you add comment in the file that this command optional?

**Comment by Fair-Exchange** [comment]
sure, have done so :)

**Comment by Fair-Exchange** [comment]
that said,

for the trading UI, also needed this:
https://github.com/discourse/mini_racer/issues/92#issuecomment-419318717

**Comment by ysv** [comment]
@Fair-Exchange could you be more specific please
Why do we need this ?

Reopen if needed

**Pull request closed without merging**
