### PR TITLE
Ensure orders are put back to matching daemon order book (fixes disappearing orders, fixes order cancelation problem, optimizes number of queries to markets)

### PR DESCRIPTION
**Pull request by yivo**

### CODE REVIEW

**Comment by mod** [comment]
@yivo is it worth writing more tests for this engine
can you compare performance with rake benchmark before and after ?

**Comment by mod** [comment]
are we able to test it?

**Comment by yivo** [comment]
@mod Sure, we are testing this on peatio.trade

**Comment by shingonoide** [comment]
@yivo we need to be able to perform `rake specs`, is there a way to run `rspec` against Peatio?

**Pull request merged**
