### PR TITLE
Ability to see Transaction ID in user interface

### PR DESCRIPTION
**Pull request by dinesh-skyach**
Ability to see Transaction ID in user interface

### CODE REVIEW

**Comment by ysv** [comment]
@dinesh-skyach If Transaction ID is empty show 'Pending'

**Comment by dinesh-skyach** [comment]
@ysv Do you mean show 'pending' in Transaction ID column?

**Comment by ysv** [comment]
@dinesh-skyach yes

**Comment by dinesh-skyach** [comment]
@ysv Done

**Comment by ysv** [comment]
@dinesh-skyach could you attach screenshots

**Comment by dinesh-skyach** [comment]
@ysv 
withdraw_done
withdraw_submitted

**Comment by ysv** [comment]
@dinesh-skyach Thanks!

**Review by mod — APPROVED** [review]

**Pull request merged**
