### PR TITLE
Replace PaymentTransaction in favor of Deposit

### PR DESCRIPTION
**Pull request by yivo**

### CODE REVIEW

**Comment by pkucherenk0** [comment]
History do not show up in the process of deposit or after it.

**Comment by pkucherenk0** [comment]
Creating new deposit's in UAH will display request in the deposit history in user interface but will not be displayed in admin panel deposits. Its is blocking the processes of accepting the deposit.

**Comment by yivo** [comment]
@pkucherenk0 scroll to the down deposit listing and you will see. it is stupid peatio admin UI

**Pull request merged**
