### PR TITLE
Various UI fixes (Bootstrap 4 migration)

### PR DESCRIPTION
**Pull request by webmix**
- Update theme dist, with Peatio colors
- Add perfect scrollbar JS vendor
- Admin sidebar scrollbar
- Fix footer in admin
- Disabling temporary ability to collpase sidebar
- fix card colors

### CODE REVIEW

**Comment by yivo** [comment]
Problems with specs.

**Comment by yivo** [comment]
@webmix Rebased your PR. Hope specs will be resolved.

**Comment by yivo** [comment]
image

This is totally invalid in context of Sprockets.

It should be just `@import 'yarn_components/perfect-scrollbar/css/perfect-scrollbar';`.

**Comment by webmix** [comment]
Thanks for the fixes @yivo 
Let's see if spec pass

**Comment by yivo** [comment]
image

**Comment by yivo** [comment]
Travis build still fails with known error (it is OK for now, we will fix it later).

https://github.com/rubykube/peatio/issues/878

image

**Pull request merged**
