### PR TITLE
Remove Withdraw#sn and all usages (fixes #802)

### LINKED ISSUE #802: Remove Withdraw#sn and all usages

### PR DESCRIPTION
**Pull request by k1T4eR**

### CODE REVIEW

**Comment by yivo** [comment]
@k1T4eR Locales aren't cleaned up. 

image

**Review by yivo — CHANGES_REQUESTED** [review]
I think you need to QA it.

image

**Comment by yivo** [comment]
image

**Review by yivo — APPROVED** [review]

**Comment by mod** [comment]
@yivo wasn't SN used in private websocket?

**Comment by yivo** [comment]
@mod In private Pusher channels Member#sn is used.

**Pull request merged**
