### PR TITLE
Remove two factor verification

### PR DESCRIPTION
**Pull request by vpetrusenko**
remove tests and WIP remove 2-factor dependencies with previous changes saving

### CODE REVIEW

**Comment by mod** [comment]
please run unit tests, and review @dkkoval

**Comment by yivo** [comment]
@vpetrusenko you have removed models but you didn't remove drop tables. Could you please generate migrations for removed models?

**Comment by yivo** [comment]
@vpetrusenko Also please remove associated translations.

**Comment by yivo** [comment]
@vpetrusenko 
- [ ] Drop tables for removed models
- [x] Remove locales for this feature
- [x] Remove leaked associations for two factor models (check `Member#two_factors`)
- [x] Remove code which references two factor features in: `app/models/member.rb`, `app/models/deposit.rb`, `app/satoshi/edit.html.slim`, `app/views/private/api_tokens/new.html.slim`, `app/views/private/api_tokens/edit.html.slim`, `app/models/withdraw.rb`, `app/helpers/two_factor_helper.rb`
- [x] Remove leaked tests for two factor auth: `spec/support/login_helper.rb`, `spec/features/sign_in_spec.rb`, `spec/features/widthdraw_spec.rb`

**Comment by yivo** [comment]
- [ ] Remove leaked JS scripts: `app/assets/javascripts/component_ui/sms_auth_verify.js.coffee`, ``
- [ ] Controller `SmsAuthsController` and specs for it

@vpetrusenko Basically grep project by `sms`. There are lot of stuff to remove.

**Comment by mod** [comment]
@vpetrusenko Please rebase on master, did you run unit tests ?
@yivo can you have someone checking out and testing everything

**Comment by vpetrusenko** [comment]
@mod already rebase on master, i should run unit tests for check if peatio works properly without two-factor?

**Comment by yivo** [comment]
@vpetrusenko Please, run tests as often as possible so you will be able to fix them step by step.

@mod Yes, sure. I will find someone.

**Comment by yivo** [comment]
@vpetrusenko So, are tests broken or they work?

**Comment by vpetrusenko** [comment]
@yivo have some errors from tests, trying to fix this

**Comment by yivo** [comment]
@vpetrusenko Got it.

**Pull request closed without merging**
