### PR TITLE
[2.0] Massive gem updates + RAILS SECURITY UPDATE

### PR DESCRIPTION
**Pull request by Amiran-Todua**

### CODE REVIEW

**Comment by Amiran-Todua** [comment]
As update to #1833.

**Comment by Amiran-Todua** [comment]
@ysv all done

**Comment by greysteil** [comment]
You might want to also update Rails to 4.2.11 here, to fix the two security vulnerabilities that were announced in it today. (I'd still love you to give Dependabot a try on this repo to automatically create dependency bumps, even if it's just for insecure dependencies.)

**Comment by Amiran-Todua** [comment]
@greysteil Thanks for this hint.

**Comment by mod** [comment]
Thanks @Amiran-Todua and @greysteil we are merging a major branch which contains gem updates
@greysteil I will try your bot on the repo.

**Comment by greysteil** [comment]
@mod - awesome! Let me know if I can help at all.

**Pull request closed without merging**
