### PR TITLE
Add automatic validation for numeric and string database table fields

### PR DESCRIPTION
**Pull request by shal**

### CODE REVIEW

**Comment by yivo** [comment]
@ashanaakh This is not what we need. Please, read the issue again.

**Comment by ashanaakh** [comment]
@yivo should I add it only to `Deposit` model?

**Comment by yivo** [comment]
@ashanaakh This is required for all models in peatio. Add to ActiveRecord::Base.

**Comment by shal** [comment]
@yivo Can you, please, explain how I to use hook `inherited` in this case?

I think we can create new class, that inherits from `ActiveRecord::Base` like
```ruby
class ClassThatInherits < ActiveRecord::Base
  validates_lengths_from_database
end
```

and use `ClassThatInherits` instead of `ActiveRecord::Base`  in models, which have limited string fields.

**Comment by yivo** [comment]
@ashanaakh This is how Rails 5 does. But it will not work good for Rails 4 so please read about inherited at Ruby sites to understand how you can use it.

**Comment by shal** [comment]
I went through models with purpose to find any length validation. Seems like there was no validations for it before 😄

**Pull request merged**
