### PR TITLE
Add missing translation for «ORDER FULFILLED» (account version reason) and fix spelling.

### PR DESCRIPTION
**Pull request by sramsden**
In server.en.yml add to enumerize.account_version.reason ... 
`order_fulfilled: ORDER FULFILLED`
 ... and also fix the spelling of "fulfilled" in every occurrence I could find.

### CODE REVIEW

**Comment by yivo** [comment]
Hi @sramsden 

Thank you for the contribution. Could you please rebase your branch to master? It seems like the branch is outdated.

**Comment by sramsden** [comment]
https://travis-ci.org/rubykube/peatio/builds/357164920
The build failed .. but I DO NOT get that error locally.
LOCALLY I get ...
```
Failures:

  1) show account info user can place a sell order by filling in the order form
     Failure/Error: page.set_rack_session(hash)

     Capybara::ElementNotFound:
       Unable to find visible field "data" that is not disabled
     # ./spec/support/inject_session.rb:5:in `inject_session'
     # ./spec/support/member_helper.rb:2:in `sign_in'
     # ./spec/features/market_spec.rb:46:in `block (2 levels) in <top (required)>'
```
Which makes sense since the trading-ui has been ejected from peatio core.
Please advise if you have a way forward from here.

**Comment by sramsden** [comment]
@yivo Why is my branch getting codeclimate errors when the failing code is from master?
Also, can you tell me why the ci build is failing.. it appears to have nothing to do with my code changes?

**Comment by yivo** [comment]
@sramsden The reason CI fails is here: https://github.com/rubykube/peatio/issues/733

As for codeclimate: I see it analyzes the code in total (only brakeman is enabled).

**Comment by sramsden** [comment]
Thanks @yivo .  I'll simply wait until one of you guys merge some other PR which will force those issues to be sorted out.

**Comment by yivo** [comment]
@sramsden Hi again. I think your PR is fine. Could you please rebase it? I am sure we can merge it ever if TravisCI build fails due to #733.

**Pull request merged**
