### PR TITLE
Fix ssl tls smtp server

### PR DESCRIPTION
**Pull request by paulokinho**

### CODE REVIEW

**Comment by mod** [comment]
@yivo I think we can cherry pick a072428
Regarding SSL I think we need to confirm and eventually make a dynamic configuration.

**Comment by yivo** [comment]
@mod We should not cherry pick https://github.com/rubykube/peatio/commit/a0724287a3aa796dfe30537027f140d77f9edd0e or it will break auth through JWT. It is not syntax error, it is safe navigation operator.

**Comment by yivo** [comment]
@mod I can confirm the configuration in master will not deal with Gmail account.

**Comment by yivo** [comment]
@paulokinho @mod I have created an issue related to this – https://github.com/rubykube/peatio/issues/239

We will make dynamic configuration.

**Comment by yivo** [comment]
Continued in #246.

**Pull request closed without merging**
