### PR TITLE
Remove legacy withdraw factories

### PR DESCRIPTION
**Pull request by elias19r**
This is an effort to remove legacy withdraw factories and use/create the ones with liability operation for their account balances.

TODO:
- [x] Remove `:legacy_btc_withdraw`
- [x] Remove `:legacy_usd_withdraw`
- [x] Remove `:legacy_eth_withdraw`, `:legacy_trst_withdraw`, `:legacy_ring_withdraw`

### CODE REVIEW

**Comment by ysv** [comment]
@elias19r Hello
Be attentive because we are going to drop altcoins and ripple from base peatio source
More info you could find here https://github.com/rubykube/peatio/pull/2168

I would like to suggest you to rebase on this pr

**Comment by elias19r** [comment]
OK, now I noticed you are doing a big refactor in branch `feature/plugable-blockchains-2`. I'll rebase this branch and check if the removal of legacy_btc_withdraw and legacy_usd_withdraw done here can still be used there.

**Comment by elias19r** [comment]
_NOTE_: `bundle exec rspec spec/api/v2/management/operations_spec.rb` is intermittent: it failed with seeds 37169, 32828, 11249 and succeeded with seed 27932.

**Comment by elias19r** [comment]
> _NOTE_: `bundle exec rspec spec/api/v2/management/operations_spec.rb` is intermittent: it failed with seeds 37169, 32828, 11249 and succeeded with seed 27932.

I can't reproduce the failures with those seeds anymore.

**Review by ysv — APPROVED** [review]

**Pull request merged**
