### PR TITLE
Add task which feeds database with demo members

### LINKED ISSUE #16: Create a demo/test database with faker and factorybot

### PR DESCRIPTION
**Pull request by yivo**
It continues https://github.com/rubykube/peatio/pull/26 and closes https://github.com/rubykube/peatio/issues/16.

### CODE REVIEW

**Comment by mod** [comment]
@yivo why not using lib/ folder ?
I am unsure of making a new folder in app/

**Comment by yivo** [comment]
@mod lib directory is commonly misunderstood and used in different way than Rails. So, we should think of lib dir like place where new gems are born, e.g. the place where we can put thing which not relate to application logic, like custom database adapters, core library extensions, some utilities, everything which you can extract to separate gem and publish. The rest lives in app.

I personally always try to follow this convention and I usually have many dirs under app. 

There are lot of discussions on the web how to organize rails app correctly, for example check good blog post: https://dockyard.com/blog/ruby/2012/02/14/love-your-lib-directory

Some popular gems like activemodel serializers, carrierwave, they all add custom dir to app which contains objects of the same responsibility. Check also trailblazer (framework over Rails) which adds concepts, decorators, operations, presenters & services to app.

**Comment by yivo** [comment]
Usually I ever move lib/tasks to app/tasks since it is more logical for me.

**Comment by mod** [comment]
I agree, but then app dir is too clumsy and lib empty.
maybe test/ ? feeders are really not part of the app but tests stack

**Comment by yivo** [comment]
@mod I believe test will be a little confusing. Maybe `/support`? I have seen it often is used for similar stuff. I can configure load & autoload paths so `/support` will behave like `/app`, also I will apply rake tasks to it.

**Comment by yivo** [comment]
`bundle exec rake feed` results in:

```
MEMBER trent.deckow@beattyoberbrunner.name xnr308le2
MEMBER miracle@jacobs.net                  2i74pzpdt
MEMBER orpha@mohr.com                      qz0xtepv4
MEMBER darien@grant.name                   ub6kiz2tl
MEMBER nikki_rohan@fisher.name             aqpcbhhl1
MEMBER eino_stiedemann@schulist.info       7zvrsy6fl
MEMBER trea@boganzulauf.info               b4iqn5mc
MEMBER randal@macejkovic.biz               frev9rfb6
MEMBER dulce@reichel.org                   xkg8731ns
MEMBER angelita@hauckdeckow.net            in76vbh3v
ADMIN  admin@peatio.tech                   ipycs8e4e
ADMIN  utototo@p33.org                     3yb7ze267
ADMIN  bonodogo@p33.org                    8a33k7nm2
ADMIN  alex____98@hotmail.com              ct9eqt3zf
```

**Comment by mod** [comment]
@yivo I am sorry I understand the idea of support/ or not commit in lib/ but here I disagree,
This is perfectly fine to put application code in lib/ and better in lib/peatio/...
also you can start and should refactor code that will go in gems in lib/gem-name/
also I use lib/ to share code and function between app/ and spec/
Please let's go classic here, I don't like overcrowded app/ folders

**Pull request merged**
