### PR TITLE
Add missing Private::DepositsController#destroy action (couldn't cancel deposit)

### PR DESCRIPTION
**Pull request by yivo**

### CODE REVIEW

**Comment by pkucherenk0** [comment]
Blocked from testing by issue with no historical data in #829

**Comment by pkucherenk0** [comment]
Have only one issue with "canceled" to start with lowercase.

**Comment by yivo** [comment]
@pkucherenk0 Can you point me with screenshot?

**Comment by pkucherenk0** [comment]
selection_043

**Pull request merged**
